Repository prgrms-web-devcourse-final-project/WEB1_1_Endpoint_BE, pull requests merged in 2024-12, with the labels that each got.

#54 [QUZ-110][FEATURE] implement game start
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePrivateApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GamePrivateController.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/Game.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameChatService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameMatchingService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayerManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePrivateService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameSettingManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
Labels: ✨ feature, 민혁

#57 [QUZ-115][FEATURE] Chnage Message Filed And Score Type to Int
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameResponse.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameLeaderboardManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameLeaderboardRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameLeaderboardRepositoryAdapter.kt
Labels: ✨ feature, 민혁

#59 [QUZ-119][FEAUTRE] Serialize Socket Message
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-infra/build.gradle.kts
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisSubscriber.kt
Labels: ✨ feature, 민혁

#61 [QUZ-120][REFACTOR] refactor fetch game set
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/GameQuiz.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizFetcher.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/feign/QuizFetcherFeignClient.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/QuizSearchInternalApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/dto/Response.kt
Labels: ♻️ refactor, 민혁

#56 [QUZ-76][FEATURE] 퀴즈 피드 API 구현
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/QuizMyApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/QuizSearchApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/QuizSearchInternalApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/dto/Request.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/dto/Response.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizFeed.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizSearchRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizSearcher.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/SearchCondition.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/UserQuizReadService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/UserQuizReadUseCase.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/repository/CustomQuizSearchRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/repository/CustomQuizSearchRepositoryImpl.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/repository/QuizSearchRepositoryAdapter.kt
Labels: ✨ feature, 수빈

#62 [QUZ-120][REFACTOR]Fetch game set to quiz service
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePrivateApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/global/exception/GlobalExceptionHandler.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizFetcher.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/feign/QuizFetcherFeignClient.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/QuizSearchInternalApi.kt
Labels: ♻️ refactor, 민혁

#65 [QUZ-41][FEATURE] Game result implement
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/global/exception/GlobalExceptionHandler.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GamePlayingController.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/RatingCalculator.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/User.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserUpdater.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswer.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerReader.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerRepository.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/user/entity/UserEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/useranswer/entity/UserAnswerRedis.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/useranswer/repository/UserAnswerRepositoryAdapter.kt
Labels: ✨ feature, 민혁

#69 [QUZ-126][REFACTOR] 유저 조회 feign 및 response 변경
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/dto/UserResponse.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/quiz/Achievement.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/quiz/UserQuizScore.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserInfo.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/feign/UserInfoFeignClient.kt
Labels: ♻️ refactor, 민우

#66 [QUZ-113][FEATURE] 매칭 서비스와 게임, 퀴즈 서비스 연동
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/MatchingServiceApplication.kt
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/sse/SseConnector.kt
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/sse/SseSender.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/game/GameFetcher.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/game/GameVO.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/MatchingUser.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/MatchingUserReader.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/MatchingUserRepository.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/UserFetcher.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/UserVO.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/UserVectorizer.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/exception/MatchingUserErrorCode.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/exception/MatchingUserException.kt
  matching-service/matching-infra/build.gradle.kts
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/adapter/GameFetcherAdapter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/client/GameRoomClient.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/dto/Response.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/entity/MatchingUserEntity.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/entity/UserEntityVO.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/AbstractEventHandler.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/Event.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/EventHandler.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/EventHandlerFactory.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/UserKafkaListener.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/quiz/QuizEvent.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/messaging/listener/quiz/QuizEventHandler.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/repository/MatchingUserRepositoryAdapter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/user/repository/UserJpaRepository.kt
  matching-service/matching-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 수빈

#70 [QUZ-127][FEATURE] GCS CDN 도메인으로 변경
  quiz-service/quiz-infra/src/main/resources/application-infra.yml
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 민우

#71 [QUZ-124][FEATURE] add async processing
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameApplicationEvent.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameMatchingService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePrivateService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/message/MessagePublisher.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/message/StreamMessage.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserUpdater.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/AbstractRedisStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/DestroyStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/GameStartStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RatingStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisPendingMessageHandler.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisStreamPublisher.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/util/RedisOperator.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/schedule/ScheduleConfig.kt
Labels: ✨ feature, 민혁

#72 [QUZ-128][FEATURE] 퀴즈 난이도 설정
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizVO.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/document/QuizDifficultyUtil.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/document/QuizDocument.kt
Labels: ✨ feature, 수빈

#73 [QUZ-129][FEATURE] change game rule
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GamePlayingController.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/Game.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/GameQuiz.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizAppender.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/quiz/QuizRedisEntity.kt
Labels: ✨ feature, 민혁

#74 [QUZ-122] gateway rate limit, circuit breaker 패턴 적용
  gateway-service/build.gradle.kts
  gateway-service/src/main/kotlin/com/grepp/quizy/api/GatewayFallbackController.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/config/RateLimiterConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/CircuitBreakerErrorCode.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/CustomCircuitBreakerException.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/webclient/UserClient.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/webclient/UserClientImpl.kt
  gateway-service/src/main/resources/application.yml
Labels: ✨ feature, 민우

#75 [QUZ-125][REFACTOR] 랜덤 매칭 로직에 RediSearch 적용
  infrastructure/docker-compose/redis/redis.yml
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingPoolManager.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingPoolRepository.kt
  matching-service/matching-infra/build.gradle.kts
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/converter/VectorArrayConverter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/repository/MatchingPoolRepositoryAdapter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/redis/config/JedisConfig.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/redis/config/RedisConfig.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/redis/util/ArrayConverter.kt
Labels: ♻️ refactor, 수빈

#76 [QUZ-130][TEST] domain module test, redis refactor
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserUpdater.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerRepository.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/FakeGameApplicationEventPublisher.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/FakeGameMessagePublisher.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/FakeGameRepository.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/FakeIdGenerator.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameAppenderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameChatServiceTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameLevelTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameManagerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameMatchingServiceTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GamePlayerManagerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GamePrivateServiceTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameReaderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameSettingManagerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameSettingTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameSubjectTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/GameTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/InviteCodeTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/PlayerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/PlayersTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/quiz/QuizAppenderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/quiz/QuizReaderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/FakeUserRepository.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/UserAppenderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/UserReaderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/UserRemoverTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/UserServiceTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/UserTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/user/UserUpdaterTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerAppenderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerReaderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/useranswer/UserAnswerTest.kt
  game-service/game-infra/build.gradle.kts
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRedisRepository.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/AbstractRedisStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/DestroyStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/GameStartStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RatingStreamConsumer.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/config/RedisStreamConfiguration.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/useranswer/repository/UserAnswerRepositoryAdapter.kt
  game-service/game-infra/src/main/resources/application-infra.yml
Labels: ♻️ refactor, ✅ test, 민혁
