Repository prgrms-web-devcourse-final-project/WEB1_1_Endpoint_BE, pull requests merged in 2024-11, with the labels that each got.

#1 [QUZ-36][FEATURE] WebSocket Configuration
  game-service/game-domain/build.gradle.kts
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/domain/game/GameMessageSender.kt
  game-service/game-infra/build.gradle.kts
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/infra/game/websocket/CustomHandshakeHandler.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/infra/game/websocket/GameWebSocketMessageSender.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/infra/game/websocket/WebSocketBrokerConfig.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/infra/game/websocket/WebSocketDestination.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/infra/game/websocket/WebSocketPrincipal.kt
  game-service/game-infra/src/main/resources/application-infra.yml
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/infra/game/websocket/GameWebSocketMessageSenderTest.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/infra/game/websocket/WebSocketBrokerConfigTest.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/infra/game/websocket/WebSocketPrincipalTest.kt
Labels: ✨ feature, 민혁

#2 [Quz-43][FEATURE] user service 작성
  user-service/user-domain/build.gradle.kts
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/AuthProvider.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/ProviderType.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/Role.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/User.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserAppender.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserId.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserProfile.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserReader.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserRemover.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserRepository.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/UserService.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/domain/user/exception/UserErrorCode.kt
  user-service/user-domain/src/test/kotlin/com/grepp/quizy/damin/user/UserServiceTest.kt
  user-service/user-infra/build.gradle.kts
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/infra/user/entity/ProviderTypeVO.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/infra/user/entity/UserEntity.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/infra/user/entity/UserProfileVO.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/infra/user/exception/UserNotFoundException.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/infra/user/repository/UserJPARepository.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/infra/user/repository/UserRepositoryAdaptor.kt
  user-service/user-infra/src/main/resources/application-infra.yml
  user-service/user-infra/src/test/kotlin/com/grepp/quizy/infra/user/UserRepositoryAdapterTest.kt
Labels: ✨ feature, 민우

#3 [QUZ-42][FEATURE] Elasticsearch Init
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/Quiz.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizType.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizVO.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/SearchedQuiz.kt
  search-service/search-domain/src/test/kotlin/com/grepp/quizy/search/domain/quiz/QuizCountTest.kt
  search-service/search-infra/build.gradle.kts
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/elasticsearch/ElasticSearchConfig.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/QuizDocument.kt
  search-service/search-infra/src/main/resources/application-infra.yml
  search-service/search-infra/src/main/resources/elastic/es-mappings.json
  search-service/search-infra/src/main/resources/elastic/es-settings.json
Labels: ✨ feature, 수빈

#4 [Quz-37][FEATURE] Redis Pub/Sub Config implement
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisPublisher.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisSubscriber.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/config/RedisEmbeddedConfig.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/config/RedisPubSubConfig.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/config/RedisRepositoryConfig.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/websocket/CustomHandshakeHandler.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/websocket/GameWebSocketMessageSender.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/websocket/WebSocketBrokerConfig.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/websocket/WebSocketDestination.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/websocket/WebSocketPrincipal.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/game/infra/websocket/GameWebSocketMessageSenderTest.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/game/infra/websocket/WebSocketBrokerConfigTest.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/game/infra/websocket/WebSocketPrincipalTest.kt
Labels: ✨ feature, 민혁

#10 [QUZ-56][FEATURE] 댓글 API 구현
  build.gradle.kts
  common/src/main/kotlin/com/grepp/quizy/common/dto/DateTime.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/HealthCheckApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/comment/CommentApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/comment/dto/CommentResponse.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/comment/dto/CreateCommentRequest.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/global/exception/QuizControllerAdvice.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/QuizApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/dto/CreateQuizRequest.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/dto/QuizResponse.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/useranswer/UserAnswerApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/config/WebConfig.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/Comment.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentAppender.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentCreateUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentDeleteUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentReadUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentReader.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentRemover.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentUpdateUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentUpdater.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentVO.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/exception/CommentErrorCode.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/exception/CommentException.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/ABTest.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/MultipleChoiceQuiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/OXQuiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/Quiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizAppender.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizCreateUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizDeleteUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizReader.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizRemover.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizTagManager.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizUpdateUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizUpdater.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizVO.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/exception/QuizErrorCode.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/exception/QuizException.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/exception/QuizNotFoundException.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/useranswer/Choice.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/useranswer/UserAnswer.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/useranswer/UserAnswerAppender.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/useranswer/UserAnswerService.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/comment/entity/CommentEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/comment/repository/CommentJpaRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/comment/repository/CommentRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/ABTestEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/MultipleChoiceQuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/OXQuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/QuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/repository/QuizRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/useranswer/entity/UserAnswerEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/useranswer/entity/UserAnswerEntityId.kt
  quiz-service/quiz-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 지원

#9 [QUZ-47][FEATURE] Keyword search api
  .DS_Store
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/HealthCheckApi.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/QuizSearchApi.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/dto/Request.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/dto/Response.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/global/dto/Slice.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/Quiz.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizDTOFactory.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizFetcher.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizMetadataCombiner.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizSearchRepository.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizSearchService.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizSearchUseCase.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizSearcher.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizType.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizVO.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizVariants.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/SearchCondition.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/SearchedQuiz.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/user/UserVO.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/elasticsearch/ElasticSearchConfig.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/QuizDocument.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDocument.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDocumentConverters.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDocumentVO.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDomainFactory.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/SortField.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/UserAnswerDocument.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/feign/QuizFetcherAdapter.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/CustomQuizSearchRepository.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/CustomQuizSearchRepositoryImpl.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/QuizElasticRepository.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/QuizSearchRepositoryAdapter.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/UserAnswerElasticRepository.kt
  search-service/search-infra/src/main/resources/application-infra.yml
  search-service/search-infra/src/main/resources/elastic/es-mappings.json
Labels: ✨ feature, 수빈

#11 [QUZ-66][FEATURE] GameRoom Setting Implementation
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameResponse.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameSettingRequest.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Game.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GamePlayerManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameSettingManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameVO.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/exception/GameErrorCode.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/exception/GameException.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/GameRedisEntity.kt
Labels: ✨ feature, 민혁

#6 [QUZ-54][FEATURE] 게이트웨이 JWT 검증 필터 추가
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/global/config/WebConfig.kt
  gateway-service/build.gradle.kts
  gateway-service/src/main/kotlin/com/grepp/quizy/config/SecurityConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/config/WebConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/jwt/JwtAuthGlobalFilter.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/jwt/JwtProvider.kt
  gateway-service/src/main/resources/application.yml
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/config/WebConfig.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/config/WebConfig.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/config/WebConfig.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/HealthCheckApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/config/WebConfig.kt
  user-service/user-infra/build.gradle.kts
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 민우

#13 [QUZ-065][FEATURE]user kick function implement
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/KickUserRequest.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Game.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameMessagePublisher.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameMessageSender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GamePlayerManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/GameRedisEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/GameWebSocketMessageSender.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/RedisPublisher.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisSubscriber.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/game/infra/websocket/GameWebSocketMessageSenderTest.kt
Labels: ✨ feature, 민혁

#12 [QUZ-69][FEATURE] 좋아요 구현
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/like/LikeApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/like/dto/LikeRequest.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/like/dto/LikeStatusCheckRequest.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/like/dto/LikeStatusResponse.kt
  quiz-service/quiz-application/app-api/src/main/resources/application.yml
  quiz-service/quiz-domain/build.gradle.kts
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentAppender.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/comment/CommentService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/like/Like.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/like/LikeManager.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/like/LikeRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/like/LikeService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/like/LikeStatus.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/ABTest.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/MultipleChoiceQuiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/OXQuiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/Quiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizCache.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizReader.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizUpdateUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizUpdater.kt
  quiz-service/quiz-infra/build.gradle.kts
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/like/entity/LikeEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/like/entity/LikeEntityId.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/like/repository/LikeJpaRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/like/repository/LikeRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/cache/QuizRedisCache.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/ABTestEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/MultipleChoiceQuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/OXQuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/QuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/repository/QuizJpaBatchRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/repository/QuizJpaBatchRepositoryImpl.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/repository/QuizJpaRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/repository/QuizRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/scheduled/QuizLikeSynchronizer.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/scheduled/SchedulingConfig.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/redis/RedisConfig.kt
  quiz-service/quiz-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 지원

#15 [QUZ-071][TEST] Game Room Domain Test
  .DS_Store
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameApi.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/domain/game/GameMessageSender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Game.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameLevel.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameStatus.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameSubject.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameVO.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/FakeGameMessagePublisher.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/FakeGameRepository.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/FakeIdGenerator.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameAppenderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GamePlayerManagerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameReaderTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameServiceTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameSettingManagerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameSettingTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/InviteCodeTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/PlayerTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/PlayersTest.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/GameRedisEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/websocket/CustomHandshakeHandler.kt
Labels: ✅ test, 민혁

#17 [QUZ-38][FEATURE] message chat implement
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameChatApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePrivateApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/ChatPayloadRequest.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameSettingPayloadRequest.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameSettingRequest.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/KickUserPayloadRequest.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/KickUserRequest.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GameChatService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/GamePrivateService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameChatServiceTest.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/GameServiceTest.kt
Labels: ✨ feature, 민혁

#18 [QUZ-75][FEATURE] 게임 퀴즈셋 API 구현
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/QuizSearchApi.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/QuizSearchInternalApi.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/dto/Request.kt
  search-service/search-application/app-api/src/main/kotlin/com/grepp/quizy/search/api/quiz/dto/Response.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/GameQuizDetail.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/GameQuizPoolUtils.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/GameQuizSearchService.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/GameQuizSearchUseCase.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizDTOFactory.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizMetadataCombiner.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizSearchRepository.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizSearcher.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizType.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/QuizVariants.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/SearchCondition.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/UserQuizSearchService.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/UserQuizSearchUseCase.kt
  search-service/search-domain/src/main/kotlin/com/grepp/quizy/search/domain/quiz/UserSearchedQuiz.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/QuizDocument.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDocument.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDocumentVO.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/QuizDomainFactory.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/document/SortField.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/CustomQuizSearchRepository.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/CustomQuizSearchRepositoryImpl.kt
  search-service/search-infra/src/main/kotlin/com/grepp/quizy/search/infra/quiz/repository/QuizSearchRepositoryAdapter.kt
Labels: ✨ feature, 수빈

#21 [QUZ-72] 로그아웃 및 토큰 재발급 기능 추가
  gateway-service/src/main/kotlin/com/grepp/quizy/config/RedisConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/GlobalErrorExceptionHandler.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/jwt/JwtAuthGlobalFilter.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/jwt/JwtValidator.kt
  gateway-service/src/main/resources/application.yml
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/UserServiceApplication.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/auth/AuthApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/api/GlobalExceptionHandler.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/api/UserControllerAdvice.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/jwt/JwtGenerator.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/jwt/JwtProvider.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/jwt/JwtValidator.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/jwt/dto/TokenResponse.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/util/CookieUtils.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/UserApi.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/CreateUserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/RedisTokenRepository.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/ReissueToken.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/TokenGenerator.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/TokenProvider.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserAppender.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserLogoutManager.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserLogoutUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserMessageSender.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReadUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReader.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReissueManager.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReissueUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserService.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/exception/UserErrorCode.kt
  user-service/user-domain/src/test/kotlin/com/grepp/quizy/damin/user/UserServiceTest.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/redis/repository/RedisTokenRepositoryAdaptor.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/redis/util/RedisUtil.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/user/messaging/publisher/UserKafkaMessagePublisher.kt
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 민우

#23 [QUZ-78][FEATURE] 중복 로그인 방지 및 유저 검증 추가
  gateway-service/src/main/kotlin/com/grepp/quizy/config/SwaggerConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/config/WebClientConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/CustomJwtException.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/JwtErrorCode.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/jwt/JwtAuthGlobalFilter.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/user/RedisTokenRepository.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/web-client/UserClient.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/web-client/UserClientImpl.kt
  gateway-service/src/main/resources/application.yml
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/oauth2/CustomOAuth2LoginSuccessHandler.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/oauth2/CustomOAuth2UserService.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/UserInternalApi.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/RedisTokenRepository.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserAppender.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserLoginManager.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserLogoutManager.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReader.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReissueManager.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserRemover.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserRepository.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserService.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserValidUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserValidator.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/exception/CustomUserException.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/exception/UserErrorCode.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/exception/UserNotFoundException.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/redis/repository/RedisTokenRepositoryAdaptor.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/redis/util/RedisUtil.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/user/repository/UserRepositoryAdaptor.kt
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 민우

#26 [QUZ-84][FEATURE] Quiz Image API
  gateway-service/src/main/kotlin/com/grepp/quizy/config/RedisConfig.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/image/FileMapper.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/image/QuizImageApi.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/ImageFile.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImage.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageManager.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageUploader.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/exception/QuizImageDomainException.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/exception/QuizImageErrorCode.kt
  quiz-service/quiz-infra/build.gradle.kts
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/gcs/config/GcsConfig.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/FileGcsUploader.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/entity/QuizImageEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/exception/QuizImageInfraException.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/repository/QuizImageJpaRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/repository/QuizImageRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 지원

#27 [QUZ-82][FEATURE] 프로필 업데이트
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/JwtErrorCode.kt
  gateway-service/src/main/resources/application.yml
  user-service/user-application/app-api/build.gradle.kts
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/oauth2/CustomOAuth2UserService.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/util/FileMapper.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/UserApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/dto/UpdateProfileRequest.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/DeleteUserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/ImageFile.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/ProfileImageUploader.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UpdateUserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/User.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserRemover.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserService.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserUpdateUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserUpdater.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserVO.kt
  user-service/user-infra/build.gradle.kts
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/gcs/GcsConfig.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/gcs/GcsFileUploader.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/user/entity/UserEntity.kt
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 민우

#32 [QUZ-84][FEATURE] 퀴즈 도메인 이미지 추가
  common/common-web/src/main/kotlin/com/grepp/quizy/web/dto/UserPrincipal.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/global/config/SwaggerConfig.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/image/QuizImageApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/like/LikeApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/QuizApi.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/dto/CreateQuizRequest.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/dto/QuizOptionRequest.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/dto/QuizOptionResponse.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quiz/dto/QuizResponse.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImage.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageManager.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizUpdateUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quiz/QuizVO.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/repository/QuizImageRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/ABTestEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/MultipleChoiceQuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/OXQuizEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quiz/entity/QuizEntityVO.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/document/QuizDocumentVO.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/document/QuizDomainFactory.kt
Labels: ✨ feature

#33 [HOTFIX] @AuthUser 쿼리파라미터 인식 오류
  game-service/game-application/app-api/build.gradle.kts
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/global/config/SwaggerConfig.kt
  matching-service/matching-application/app-api/build.gradle.kts
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/config/SwaggerConfig.kt
  user-service/user-application/app-api/build.gradle.kts
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/config/SwaggerConfig.kt
Labels: 🚑 hotfix

#25 [QUZ-86][FEATURE] 안 푼 문제 검색 API 구현
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/global/exception/QuizControllerAdvice.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/quizread/QuizSearchApi.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizMetadataCombiner.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizSearchRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizSearcher.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/UserQuizSearchService.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/UserQuizSearchUseCase.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/useranswer/UserAnswerReader.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/useranswer/UserAnswerRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/document/QuizDocument.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/repository/CustomQuizSearchRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/repository/CustomQuizSearchRepositoryImpl.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/quizread/repository/QuizSearchRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/useranswer/repository/UserAnswerJpaRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/useranswer/repository/UserAnswerRepositoryAdapter.kt
Labels: ✨ feature, 수빈

#31 [QUZ-40][FEATURE] transmit quiz implement
  .DS_Store
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameManageService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameQuizAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameQuizReader.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/GameQuiz.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizFetcher.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizReader.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/quiz/QuizRepository.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/FakeGameRepository.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/feign/QuizFetcherFeignClient.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/entity/GameRedisEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/quiz/QuizRedisEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/quiz/QuizRedisRepository.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/quiz/QuizRepositoryAdaptor.kt
Labels: ✨ feature, 민혁

#30 [QUZ-88][FEATURE] user-service api 작성
  build.gradle.kts
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  user-service/user-application/app-api/build.gradle.kts
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/HealthCheckApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/auth/AuthApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/UserApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/user/dto/UserResponse.kt
  user-service/user-application/app-api/src/main/resources/application.yml
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/game/GameClient.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/game/RatingReader.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/game/UserRating.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/quiz/QuizClient.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/quiz/QuizScoreReader.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/quiz/UserQuizScore.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/InterestOnboardingEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserDeleteUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserInfo.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReadUseCase.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserRemover.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserService.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserUpdater.kt
  user-service/user-domain/src/test/kotlin/com/grepp/quizy/damin/user/UserServiceTest.kt
  user-service/user-infra/build.gradle.kts
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/feign/FeignConfig.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/feign/UserInfoFeignClient.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/user/messaging/listener/UserKafkaListener.kt
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 민우

#36 [HOTFIX CORS 설정 변경
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/global/config/WebConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/config/WebConfig.kt
  gateway-service/src/main/resources/application.yml
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/config/WebConfig.kt
  quiz-service/quiz-application/app-api/src/main/kotlin/com/grepp/quizy/quiz/api/global/config/WebConfig.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/config/WebConfig.kt
Labels: 🚑 hotfix, 민우

#37 [QUZ-93][HOTFIX] dev 환경에서 로그인이 안되는 이슈 수정
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  gateway-service/src/main/resources/application.yml
  user-service/user-application/app-api/src/main/resources/application.yml
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/user/messaging/listener/UserKafkaListener.kt
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: 🚑 hotfix, 민우

#40 [QUZ-95][FEATURE] 로그인 시 redirect 방식 사용
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/oauth2/CustomOAuth2LoginFailureHandler.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/oauth2/CustomOAuth2LoginSuccessHandler.kt
  user-service/user-application/app-api/src/main/resources/application.yml
Labels: ✨ feature, 민우

#35 [QUZ-39][FEAUTRE] quiz answer submit implement
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePlayingApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/SubmitAnswerRequest.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameLeaderboardManager.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameLeaderboardRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameManageService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameMessageSender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GamePlayService.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameQuizAppender.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameQuizReader.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameQuizRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameRepository.kt
  game-service/game-domain/src/test/kotlin/com/grepp/quizy/game/domain/game/FakeGameRepository.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/GameWebSocketMessageSender.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameLeaderboardRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameQuizRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRepositoryAdapter.kt
  game-service/game-infra/src/test/kotlin/com/grepp/quizy/game/infra/websocket/GameWebSocketMessageSenderTest.kt
Labels: ✨ feature, 민혁

#43 [QUZ-96][HOTFIX] refreshToken 쿠키 등록 방식 변경
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/auth/AuthApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/util/CookieUtils.kt
Labels: 🚑 hotfix, 민우

#41 [QUZ-74][FEATURE] websocket exception handling
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameChatController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameMatchingApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GameMatchingController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePlayingController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePrivateApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePrivateController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/global/exception/GlobalWebSocketExceptionHandler.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/user/messaging/listener/UserKafkaListener.kt
Labels: ✨ feature, 민혁

#44 [QUZ-97][FIX] kafka consume and api error
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePlayingApi.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserCreatedEvent.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/user/entity/UserEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/user/messaging/listener/UserKafkaListener.kt
  game-service/game-infra/src/main/resources/application-infra.yml
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/CreateUserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/DeleteUserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UpdateUserEvent.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserAppender.kt
Labels: 🐛 bugfix, 민혁

#45 [QUZ-99][FIX] subject,level request string
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/GamePrivateApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameCreateRequest.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameSettingPayloadRequest.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/global/exception/GlobalExceptionHandler.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GameChatController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GameMatchingController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GamePlayingController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/game/GamePrivateController.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/controller/global/exception/GlobalWebSocketExceptionHandler.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/Message.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/exception/GameErrorCode.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/exception/GameException.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
Labels: 🐛 bugfix, 민혁

#46 [QUZ-99][HOTFIX] matching enum description
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
Labels: 🚑 hotfix, 민혁

#47 [QUZ-99][HOTFIX] use data class for response
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameResponse.kt
Labels: 🚑 hotfix, 민혁

#48 [QUZ-100][FEATURE] implement internal API to retrieve rating
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/user/InternalUserApi.kt
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/user/dto/UserRatingResponse.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserReader.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserRepository.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/user/UserService.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/user/repository/UserJpaRepository.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/user/repository/UserRepositoryAdaptor.kt
Labels: ✨ feature, 민혁

#49 [QUZ-94][FIX][REFACTOR] 유저 서비스 버그 수정
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/global/RedisUtil.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/jwt/JwtValidator.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/user/RedisTokenRepository.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/auth/AuthApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/oauth2/CustomOAuth2LoginSuccessHandler.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/game/UserRating.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/quiz/UserQuizScore.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/RedisTokenRepository.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserLogoutManager.kt
  user-service/user-domain/src/main/kotlin/com/grepp/quizy/user/domain/user/UserReissueManager.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/feign/UserInfoFeignClient.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/redis/repository/RedisTokenRepositoryAdaptor.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/redis/util/RedisUtil.kt
  user-service/user-infra/src/main/kotlin/com/grepp/quizy/user/infra/user/messaging/listener/UserKafkaListener.kt
  user-service/user-infra/src/main/resources/application-infra.yml
Labels: 🐛 bugfix, ♻️ refactor, 민우

#38 [QUZ-92][FEATURE] 퀴즈 검색 시 빠진 데이터 추가
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageManager.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/image/QuizImageRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizDTOFactory.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/QuizMetadataCombiner.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/quizread/UserSearchedQuiz.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/user/User.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/user/UserReader.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/user/UserRepository.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/user/UserVO.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/user/exception/UserErrorCode.kt
  quiz-service/quiz-domain/src/main/kotlin/com/grepp/quizy/quiz/domain/user/exception/UserException.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/image/repository/QuizImageRepositoryAdapter.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/entity/UserEntity.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/messaging/listener/UserCreatedEventConsumer.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/messaging/listener/UserDeletedEventConsumer.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/messaging/listener/UserEvents.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/messaging/listener/UserUpdatedEventConsumer.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/repository/UserJpaRepository.kt
  quiz-service/quiz-infra/src/main/kotlin/com/grepp/quizy/quiz/infra/user/repository/UserRepositoryAdaptor.kt
  quiz-service/quiz-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 수빈

#50 [QUZ-101] user bugfix
  gateway-service/src/main/kotlin/com/grepp/quizy/config/WebConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/exception/GlobalErrorExceptionHandler.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  gateway-service/src/main/resources/application.yml
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/auth/AuthApi.kt
  user-service/user-application/app-api/src/main/kotlin/com/grepp/quizy/user/api/global/security/SecurityConfig.kt
Labels: 🐛 bugfix, 민우

#34 [QUZ-83][FEATURE] 게임 랜덤 매칭 구현
  matching-service/matching-application/app-api/build.gradle.kts
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/game/GameMatchingApi.kt
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/sse/SseConnector.kt
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/sse/SseEmitterRepository.kt
  matching-service/matching-application/app-api/src/main/kotlin/com/grepp/quizy/matching/api/sse/SseSender.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/game/GameFetcher.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/game/GameVO.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingConstants.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingEventHandler.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingEventPublishers.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingEvents.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingManager.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingPoolManager.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingPoolRepository.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingQueueRepository.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingService.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingUseCase.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/MatchingValidator.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/match/UserStatus.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/UserFetcher.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/UserVO.kt
  matching-service/matching-domain/src/main/kotlin/com/grepp/quizy/matching/domain/user/UserVectorizer.kt
  matching-service/matching-infra/build.gradle.kts
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/feign/config/FeignConfig.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/feign/exception/OtherServerBadRequestException.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/adapter/GameFetcherAdapter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/client/GameRoomClient.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/dto/GameRoomIdRequest.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/game/dto/GameRoomIdResponse.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/config/MatchingRedisConfig.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/config/MatchingRedisPubsubConfig.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/converter/MatchingDeserializer.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/converter/VectorArrayConverter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/dto/MatchingDTO.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/pubsub/MatchingRedisPublisher.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/pubsub/MatchingRedisSubscriber.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/repository/MatchingPoolRepositoryAdapter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/match/repository/MatchingQueueRepositoryAdapter.kt
  matching-service/matching-infra/src/main/kotlin/com/grepp/quizy/matching/infra/redis/RedisConfig.kt
  matching-service/matching-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 수빈

#52 [QUZ-101][HOTFIX] sockJS 웹소켓 연결 안되는 이슈 수정
  gateway-service/src/main/kotlin/com/grepp/quizy/config/SecurityConfig.kt
  gateway-service/src/main/kotlin/com/grepp/quizy/global/AuthGlobalFilter.kt
  gateway-service/src/main/resources/application.yml
Labels: 🚑 hotfix, 민우

#53 [QUZ-109][BUGFIX] fix socket message
  game-service/game-application/app-api/src/main/kotlin/com/grepp/quizy/game/api/game/dto/GameResponse.kt
  game-service/game-domain/src/main/kotlin/com/grepp/quizy/game/domain/game/GameVO.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/entity/GameRedisEntity.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/game/repository/GameRepositoryAdapter.kt
  game-service/game-infra/src/main/kotlin/com/grepp/quizy/game/infra/redis/RedisSubscriber.kt
Labels: 🐛 bugfix, 민혁
